services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins

    container_name: jenkins

    user: root

    ports:
      - "8080:8080"
      - "50000:50000"

    volumes:
      - dados_jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - devops

  container-test:
    image: maven:3.9-eclipse-temurin-21

    working_dir: /app

    volumes:
      - .:/app

    command: mvn test

    networks:
      - devops

networks:
  devops:

volumes:
  dados_jenkins: